"""The device ``.cpp`` (AscendC) translation unit: one kernel and one shim per function.

Two passes over each function and nothing between them: one writes the
declaration a caller sees without entering the body, the other writes the
definition by walking it. Unlike the CUDA unit, an Ascend unit states no
geometry of its own -- every launch spends its own ``grid_x`` through its own
shim -- so kernels launched at different geometries may share one unit.
"""

from __future__ import annotations

from tilefoundry.codegen.ascend.abi import kernel_arguments, kernel_signature
from tilefoundry.codegen.ascend.context import AscendCodegenContext
from tilefoundry.codegen.linkable import LinkableFunction, LinkableModule
from tilefoundry.codegen.registry import CodeGenerator
from tilefoundry.codegen.signature import CallableSignature
from tilefoundry.ir.core.module import Module
from tilefoundry.ir.tir.prim_function import PrimFunction
from tilefoundry.target import Target

_ASCEND_PROGRAM_PREAMBLE = "\n".join(
    (
        "// Auto-generated by tilefoundry.codegen (ascend device unit). Do not edit by hand.",
        "#include <kernel_operator.h>",
        "#include <tilefoundry/runtime/ascend/runtime.h>",
        "",
        "using namespace AscendC;",
    )
)


def _emit_function(fn: PrimFunction, ctx: AscendCodegenContext) -> LinkableFunction:
    """*fn* in both of its positions, written from the one convention it is called by.

    A caller can name the shim and nothing else, so that is what the
    declaration states; the kernel is defined beside it and named only here.
    """
    shim = ctx.signature_of(fn)
    kernel = kernel_signature(shim, fn.name)
    return LinkableFunction(
        name=fn.name,
        declaration=f'extern "C" void {shim.name}({ctx.parameters(shim, exported=True)});',
        definition=ctx.capture(lambda scope: _define(fn, shim, kernel, scope)),
    )


def _define(
    fn: PrimFunction,
    shim: CallableSignature,
    kernel: CallableSignature,
    ctx: AscendCodegenContext,
) -> None:
    """The kernel and the shim that launches it, in that order."""
    _define_kernel(fn, kernel, ctx)
    ctx.blank()
    _define_shim(shim, kernel, ctx)


def _define_kernel(
    fn: PrimFunction, kernel: CallableSignature, ctx: AscendCodegenContext
) -> None:
    """The ``__global__ __aicore__`` kernel: what it was told, then what it runs."""
    ctx.emit(
        f"__global__ __aicore__ void {kernel.name}({ctx.parameters(kernel)}) {{"
    )
    ctx.indent()
    ctx.emit_node(fn)
    ctx.dedent()
    ctx.emit("}")


def _define_shim(
    shim: CallableSignature, kernel: CallableSignature, ctx: AscendCodegenContext
) -> None:
    """The ``extern "C"`` shim: spend the launch geometry on the default stream."""
    grid_x, _block_x, _smem = (sig.name for sig in shim.trailing)
    ctx.emit(f'extern "C" void {shim.name}({ctx.parameters(shim, exported=True)}) {{')
    ctx.indent()
    ctx.emit(
        f"{kernel.name}<<<{grid_x}, nullptr, nullptr>>>({kernel_arguments(kernel, ctx)});"
    )
    ctx.dedent()
    ctx.emit("}")


def emit_ascend_module(
    module: Module, ascend_fns: tuple[PrimFunction, ...], target: Target, ctx: AscendCodegenContext
) -> LinkableModule:
    """Emit the device ``.cpp`` (AscendC) linkable module for one topology domain."""
    kernels = tuple(fn for fn in ascend_fns if fn.target == target)
    if not kernels:
        raise ValueError(f"emit_ascend_module: module {module.name!r} has no Ascend device kernels")
    functions = tuple(_emit_function(fn, ctx) for fn in kernels)
    return LinkableModule(
        target="ascend",
        language="asc",
        functions=functions,
        preamble=_ASCEND_PROGRAM_PREAMBLE,
    )


ASCEND_CODE_GENERATOR = CodeGenerator(emit_ascend_module)


__all__ = ["ASCEND_CODE_GENERATOR", "emit_ascend_module"]
